#!/bin/bash

sudo apt update -y && sudo apt upgrade -y

#installing BUILD-ESSENTIAL
echo "----| Installing build-essential |-----"
sudo apt-get install -y build-essential

#installing BRAVE BROWSER
echo "-----| Installing BRAVE BROWSER |-----"
sudo apt install apt-transport-https curl -y

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update -y
sudo apt install brave-browser -y

#installing GOOGLE CHROME
echo "----| Installing GOOGLE CHROME |-----"
sudo apt update -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

#installing VISUAL STUDIO CODE
echo "----| Installing VISUAL STUDIO CODE |-----"
sudo apt-get install wget gpg -y
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg
sudo apt install apt-transport-https -y
sudo apt update -y
sudo apt install code -y # or code-insiders

#installing DISCORD
echo "----| Installing DISCORD |-----"
sudo snap install discord

#installing VLC
echo "----| Installing VLC |-----"
sudo apt install vlc -y

#installing ANYDESK
echo "----| Installing ANYDESK |-----"
sudo apt update -y && sudo apt upgrade -y
wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -
echo "deb http://deb.anydesk.com/ all main" | sudo tee /etc/apt/sources.list.d/anydesk-stable.list
sudo apt update -y && sudo apt upgrade -y
sudo apt install anydesk -y

#installing FILEZILLA
echo "----| Installing FILEZILLA |-----"
sudo apt-get update
sudo apt-get install filezilla -y

#installing GITHUB DESKTOP
echo "----| Installing GITHUB DESKTOP |-----"
sudo wget https://github.com/shiftkey/desktop/releases/download/release-3.1.1-linux1/GitHubDesktop-linux-3.1.1-linux1.deb
sudo apt-get install gdebi-core -y
sudo gdebi GitHubDesktop-linux-3.1.1-linux1.deb

#installing R and R STUDIO (Should contain setup files inside folder)
echo "----| Installing R and R STUDIO |-----"
sudo apt update
sudo apt install r-base -y
sudo dpkg -i rstudio-2022.07.2-576-amd64.deb

#installing CISCO PACKET TRACER (Should contain setup files inside folder)
echo "----| Installing CISCO PACKET TRACER |-----"
sudo dpkg -i CiscoPacketTracer_820_Ubuntu_64bit.deb

#installing VIRTUAL BOX
echo "----| Installing VIRTUAL BOX |-----"
sudo apt-get update
sudo apt-get install virtualbox -y

#installing PYTHON3
echo "----| Installing PYTHON3 |-----"
sudo apt-get install -y python3

#installing NET-TOOLS
echo "----| Installing NET-TOOLS |-----"
sudo apt-get install -y net-tools

#installing GIT
echo "----| Installing GIT |-----"
sudo apt-get install -y git
#git config --global user.name "<Your Name>"
#git config --global user.email "<Your Email>"

#installing GIT CLI
echo "----| Installing GIT CLI |-----"
sudo apt install -y gh
#gh config login

#installing MONITORING APPS
echo "----| Installing MONITORING APPS |-----"
sudo apt-get install nvtop -y
sudo apt-get install htop -y

#installing NODE JS v18.x
echo "----| Installing NODE JS v18.x |-----"
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\ sudo apt-get install -y nodejs

sudo apt autoremove
